### ISSUE TITLE
Test failures with scikit-learn==1.6

### ISSUE THREAD

**Issue by jeongyoonlee** [uber/causalml#808]
**Describe the bug**

Build tests are failing with the error from the latest scikit-learn==1.6 as follows ([link](https://github.com/uber/causalml/actions/runs/12319960069/job/34388195556?pr=806)):
```
AttributeError: 'super' object has no attribute '__sklearn_tags__'
```

**To Reproduce**

**Expected behavior**
Passing all tests.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. macOS, Windows, Ubuntu]
 - Python Version: [e.g. 3.6, 3.7]
 - Versions of Major Dependencies (`pandas`, `scikit-learn`, `cython`): [e.g. `pandas==0.25`, `scikit-learn==0.22`, `cython==0.28`]

**Additional context**
https://github.com/scikit-learn/scikit-learn/issues/30479
https://scikit-learn.org/1.5/developers/develop.html#rolling-your-own-estimator

**Comment by jeongyoonlee** [comment]
XGBRegressor causes it in xgboost <= 2.1.3. The issue is fixed in the master branch ([PR](https://github.com/dmlc/xgboost/pull/11021)) but hasn't yet been released. We can pin scikit-learn<1.6.0 temporarily until the fix gets released.

**Comment by pepi99** [comment]
Using scikit-learn<1.6.0 doesn't fix the issue for me. Which exact version of sklearn are you using @jeongyoonlee ?

**Comment by rs517** [comment]
I encountered the same issue, and installing scikit-learn version 1.5.2 resolved it on my end. You can try:
`!pip3 install scikit-learn==1.5.2`
This worked consistently in my environment. Hope it helps!

**Comment by ju4nv1e1r4** [comment]
The same error is appearing for me, but related to KerasRegressor. Even using sklearn version 1.5.2, the error persists.

**Comment by jeongyoonlee** [comment]
Failures with any custom regressor using scikit-learn like APIs are likely
caused by the recent change/check introduced by scikit-learn==1.6.

If you encounter it, make sure you uninstall scikit-learn 1.6 and install
an earlier version. 1.5.2 worked for me.

**Comment by Leonievb** [comment]
Had the same issue with xgboost (2.1.3) and setting scikit-learn to 1.5.2 fixed it for me

**Comment by ju4nv1e1r4** [comment]
Apparently if you use the keras wrapper (KerasRegressor), you can't. lol

**Comment by pepi99** [comment]
It finally seems to have worked for me. Please, first do pip uninstall scikit-learn and only after that do pip install scikit-learn==1.5.2 

The versions that are working for me: 
Scikit-learn: 1.5.2
XGBoost: 2.1.3

**Comment by Ahmed0Ehab** [comment]
try to use 1.5.2 version of scikit-learn
xgboost <= 2.1.3
it work with me

**Comment by AdamGovier** [comment]
> Apparently if you use the keras wrapper (KerasRegressor), you can't. lol

Did you find a fix?

**Comment by AdamGovier** [comment]
> > > Apparently if you use the keras wrapper (KerasRegressor), you can't. lol
> > 
> > 
> > Did you find a fix?
> 
> My fix is: not using this one haha But I found other framework to solve my problem

I ended up not even using sckit-learn 😂for my keras model haha

**Comment by ju4nv1e1r4** [comment]
> > > > Apparently if you use the keras wrapper (KerasRegressor), you can't. lol
> > > 
> > > 
> > > Did you find a fix?
> > 
> > 
> > My fix is: not using this one haha But I found other framework to solve my problem
> 
> I ended up not even using sckit-learn 😂for my keras model haha

Same energy here haha

**Comment by jeongyoonlee** [comment]
xgboost==2.1.4 fixed the compatibility issue with scikit-learn==1.6. For Keras, I recommend its official scikit-learn API wrappers, e.g., keras.wrappers.SKLearnClassifier and SKLearnRegressor, instead of using a third-party wrapper API, e.g., scikeras.
